Repository kaltura/playkit-js, pull requests merged in 2018-11, with the labels that each got.

#301 fix(FEC-8633): HLS fairplay fails with multiple players or consecutive playbacks
  src/drm/fairplay.js
  src/engines/html5/media-source/adapters/fairplay-drm-handler.js
  src/engines/html5/media-source/adapters/native-adapter.js
  test/src/drm/fairplay.spec.js
  test/src/engines/html5/media-source/adapters/fairplay-drm-handler.spec.js
Labels: Priority: High, Type: Bug

#302 fix(FEC-8621): player destroy event is not dispatched
  src/player.js
  test/src/player.spec.js
Labels: Type: Bug

#305 fix: add handle media error
  src/engines/html5/html5.js
Labels: Type: Bug

#308 fix(FEC-8668): inline styled vtt parser crash
  src/track/text-track-display.js
Labels: Type: Bug

#309 fix(FEC-8695): reset/destroy engine only after all services are destroyed
  src/player.js
Labels: Type: Bug

#313 fix(FEC-8712): replay button does not display when using a non liner ad
  src/ads/ads-controller.js
  src/player.js
Labels: Type: Bug

#319 feat(FEC-8639): fairplay uDRM error handling refining
  src/engines/html5/media-source/adapters/fairplay-drm-handler.js
Labels: Priority: Medium, Type: Feature
