Repository kaltura/playkit-js, pull requests merged in 2018-12, with the labels that each got.

#317 fix(FEC-8714): change media doesn't work after player.destroy() on iOS
  src/player.js
Labels: Priority: High, Type: Bug

#320 fix(FEC-8715): if label does not exist in manifest use the language property
  docs/configuration.md
  src/track/text-track.js
  test/src/engines/html5/media-source/adapters/native-adapter.spec.js
Labels: Priority: High, Type: Bug

#316 fix(FEC-8722): more than one caption is checked at the caption menu
  src/player.js
Labels: Priority: Medium, Type: Bug

#322 chore: patch 0.42.1
  CHANGELOG.md
  package.json
Labels: Type: Maintenance

#318 feat(FEC-8682): end screen
  src/state/state-manager.js
  test/src/state/state-manger.spec.js
Labels: Priority: High, Type: Feature

#323 feat(FEC-8147): set default settings for ABR settings
  src/player-config.js
  src/player-config.json
  src/player.js
Labels: Type: Feature

#321 fix(FEC-8714): removing static video element from the engine
  flow-typed/types/video-element-store.js
  src/engines/html5/html5.js
  src/player.js
Labels: Priority: High, Type: Bug

#327 fix(FEC-7444): when selecting fullscreen in android captions size is too large
  src/track/text-track-display.js
Labels: Priority: Medium, Type: Bug

#331 fix(FEC-8779): change media does not work if external caption is shown
  src/track/external-captions-handler.js
Labels: Priority: High, Type: Bug

#330 feat(FEC-8700): add config option to specify DRM system
  docs/configuration.md
  flow-typed/interfaces/engine.js
  flow-typed/types/drm-config.js
  src/drm/base-drm-protocol.js
  src/drm/fairplay.js
  src/engines/html5/html5.js
  src/engines/html5/media-source/adapters/native-adapter.js
  src/engines/html5/media-source/media-source-provider.js
  src/player-config.js
  src/player.js
  test/src/drm/fairplay.spec.js
  test/src/engines/html5/media-source/adapters/native-adapter.spec.js
  test/src/engines/html5/media-source/adapters/test-adapters/test-adapters.js
  test/src/engines/html5/media-source/media-source-provider.spec.js
Labels: Priority: High, Type: Feature

#329 fix(FEC-8770): iOS - captions style it applies for both players in the same page
  src/player.js
Labels: Priority: Medium, Type: Bug
