Repository kaltura/playkit-js, pull requests merged in 2018-06, with the labels that each got.

#242 fix(FEC-8330): remove 'timeupdate' logs
  src/state/state-manager.js
Labels: Priority: Medium

#239 feat(FEC-8046): 360 support
  src/error/category.js
  src/error/code.js
  src/event/event-manager.js
  src/event/event-type.js
  src/player.js
  src/utils/util.js
  test/src/event/event-type.spec.js
Labels: Priority: High, Type: Feature

#243 chore(FEC-8331): expose the anonymous flag on session object
  flow-typed/types/session-config.js
Labels: Type: Feature

#244 fix(FEC-8347): video is not playing 360 when adTagUrl empty
  src/player.js
  test/src/player.spec.js
Labels: Priority: Medium, Type: Bug
