Repository kaltura/playkit-js, pull requests merged in 2018-07, with the labels that each got.

#250 fix(FEC-8365): srt files are not shown
  src/track/external-captions-handler.js
  test/src/track/external-captions-handler.spec.js
Labels: Priority: High

#261 fix(FEC-8386): Kava analytics retrieved by default on OTT
  src/plugin/plugin-manager.js
  test/src/plugin/plugin-manager.spec.js
Labels: Priority: High, Type: Bug

#263 fix(FEC-7935): fix text selection logic with hlsjs
  src/engines/html5/html5.js
  src/engines/html5/media-source/adapters/native-adapter.js
  src/engines/html5/media-source/base-media-source-adapter.js
  src/player.js
  test/src/engines/html5/media-source/adapters/native-adapter.spec.js
  test/src/player.spec.js
Labels: Type: Bug

#265 feat(FEC-8390, FEC-8246): support 608/708 captions
  docs/configuration.md
  src/engines/html5/media-source/adapters/native-adapter.js
  src/player-config.json
  src/player.js
  test/src/engines/html5/media-source/adapters/native-adapter.spec.js
Labels: Priority: High, Type: Bug

#267 fix(FEC-8419): double captions on ios when toggling fullscreen
  src/player.js
  test/src/player.spec.js
  test/src/track/external-captions-handler.spec.js
Labels: Priority: Medium

#270 fix: subtitles font size is too small on mobile
  src/track/text-track-display.js
Labels: Priority: High, Type: Bug

#272 feat: expose logger util
  src/playkit.js
Labels: Priority: High

#274 feat(FEC-8269): add playback loop support
  docs/configuration.md
  src/player-config.json
  src/player.js
Labels: Type: Feature
