Repository kaltura/playkit-js, pull requests merged in 2018-09, with the labels that each got.

#287 feat: emit CHANGE_SOURCE_ENDED on first media load as well
  src/player.js
Labels: Type: Feature

#275 fix(FEC-8440): add critical error when no engine to play source
  src/error/code.js
  src/player.js
  test/src/player.spec.js
Labels: Type: Bug

#288 feat: ads controller
  flow-typed/interfaces/ads-controller-provider.js
  flow-typed/interfaces/ads-controller.js
  src/ads/ads-controller.js
  src/controller/controller-provider.js
  src/event/event-type.js
  src/player.js
  src/plugin/plugin-manager.js
  test/src/player.spec.js
Labels: Priority: High, Type: Feature
