Repository kaltura/playkit-js, pull requests merged in 2018-04, with the labels that each got.

#207 fix(FEC-8090): after disabling captions and toggling full screen the last caption frame is displayed
  src/player.js
Labels: Priority: Medium

#209 fix(FEC-8108): no playback after preroll - android browser
  src/player.js
Labels: Priority: High, Type: Bug

#212 feat: clear metadata and sources on reset
  src/player.js
Labels: Priority: Medium, Type: Feature

#220 feat: media loaded event
  dist/playkit.js
  dist/playkit.js.map
  src/event/event-type.js
  src/player.js
  test/src/event/event-type.spec.js
  test/src/player.spec.js
Labels: Priority: High, Type: Feature
