Repository kaltura/playkit-js, pull requests merged in 2019-07, with the labels that each got.

#369 feat(FEC-9145): support non sibling video tags
  flow-typed/interfaces/engine-decorator-provider.js
  flow-typed/interfaces/engine-decorator.js
  flow-typed/interfaces/engine.js
  src/ads/ads-controller.js
  src/engines/base-engine-decorator.js
  src/engines/engine-decorator.js
  src/player.js
  src/playkit.js
Labels: Priority: High, Type: Feature

#377 feat(FEC-9158): preload chain
  src/engines/engine-decorator.js
  src/middleware/playback-middleware.js
  src/player.js
Labels: Priority: High

#375 feat(FEC-9227): support reInit of MSE
  docs/configuration.md
  flow-typed/interfaces/engine-decorator.js
  flow-typed/interfaces/engine.js
  flow-typed/interfaces/media-source-adapter.js
  flow-typed/types/playback-config.js
  src/engines/html5/html5.js
  src/engines/html5/media-source/adapters/native-adapter.js
  src/engines/html5/media-source/base-media-source-adapter.js
  src/player-config.js
  src/player.js
  test/src/engines/html5/html5.spec.js
Labels: Type: Feature

#378 fix(FEC-9237): add app protocol to playkit utils
  src/utils/util.js
Labels: Type: Bug

#380 fix(FEC-9261): playback doesn't play with non-linear ads
  src/player.js
Labels: Type: Bug

#379 fix(FEC-9243): external subtitles fail on safari due to invalid cue attribute
  src/track/text-track-display.js
  src/track/vtt-cue.js
Labels: Type: Bug

#381 fix(FEC-9262): playback doesn't return to start after playback with ads in LG TV
  flow-typed/interfaces/engine-decorator.js
  flow-typed/interfaces/engine.js
  flow-typed/interfaces/media-source-adapter.js
  src/engines/html5/html5.js
  src/engines/html5/media-source/base-media-source-adapter.js
  src/player.js
Labels: Type: Bug
