Repository kaltura/playkit-js, pull requests merged in 2019-12, with the labels that each got.

#412 fix(FEC-9480): there isn't event for play promise failed just autoplay failed
  src/engines/html5/html5.js
  src/event/event-type.js
  src/player.js
Labels: Type: Bug

#423 fix(FEC-9527): The poster is hidden when auto play is failed
  src/player.js
  test/src/player.spec.js
Labels: Priority: High, Type: Bug

#426 chore: ad layout tests
  src/ads/ads-controller.js
  test/src/ads/ads-controller.spec.js
Labels: Type: Maintenance

#424 fix(FEC-9513): bumper - endless spinner when auto play is failed
  flow-typed/interfaces/engine.js
  src/ads/ad-event-type.js
  src/engines/html5/html5.js
  src/player.js
  test/src/player.spec.js
Labels: Priority: High, Type: Bug

#428 feat(FEC-9452): async request/response filter handlers
  docs/configuration.md
  src/engines/html5/media-source/adapters/fairplay-drm-handler.js
  src/engines/html5/media-source/adapters/native-adapter.js
  test/src/engines/html5/media-source/adapters/fairplay-drm-handler.spec.js
  test/src/engines/html5/media-source/adapters/native-adapter.spec.js
Labels: Priority: High, Type: Feature

#427 feat(FEC-9474): ad layout - time definitions
  docs/configuration.md
  flow-typed/types/ad-break.js
  src/ads/ads-controller.js
  test/src/ads/ads-controller.spec.js
Labels: Priority: High, Type: Feature

#430 fix(FEC-9583): race condition on load ios playback
  src/engines/html5/media-source/adapters/native-adapter.js
Labels: Type: Bug
