Repository kaltura/playkit-js, pull requests merged in 2019-08, with the labels that each got.

#383 fix(FEC-9274): older browser doesn't support cue.align=center
  src/track/text-track-display.js
Labels: Type: Bug

#384 fix(FEC-9277): inBrowserFullscreen doesn't work on ios
  src/fullscreen/fullscreen-controller.js
  test/src/fullscreen/fullscreen-controller.spec.js
Labels: Type: Bug

#386 fix(FEC-9283): trigger RESIZE events in Firefox
  src/assets/style.css
Labels: Type: Bug

#393 fix(FEC-9291): player without engine get error after reset
  src/player.js
Labels: Type: Bug

#392 feat(FEC-9137): DRM protocol selection
  docs/api.md
  src/drm/base-drm-protocol.js
  src/drm/drm-support.js
  src/drm/fairplay.js
  src/engines/html5/media-source/adapters/native-adapter.js
  test/src/drm/drm-support.spec.js
  test/src/drm/fairplay.spec.js
  test/src/engines/html5/media-source/adapters/native-adapter.spec.js
Labels: Type: Feature

#391 feat(FEC-9271): expose interface and methods to enable customizing DRM request/response
  docs/configuration.md
  flow-typed/types/network-config.js
  flow-typed/types/player-options.js
  flow-typed/types/request-types.js
  flow-typed/types/request.js
  src/engines/html5/media-source/adapters/fairplay-drm-handler.js
  src/engines/html5/media-source/adapters/native-adapter.js
  src/player-config.js
  src/playkit.js
  src/request-type.js
Labels: Priority: High, Type: Feature

#394 fix: browser detection for samsung
  src/utils/env.js
Labels: Type: Bug
