Repository kaltura/playkit-js, pull requests merged in 2019-01, with the labels that each got.

#338 docs(FEC-8751): add support for ima playAdsAfterTime setting
  docs/configuration.md
Labels: Priority: High, Type: Docs, Type: Feature

#339 fix(FEC-8829, FEC-8807): native adapter throws an error after 30 seconds pause
  docs/configuration.md
  src/engines/html5/media-source/adapters/native-adapter.js
  src/player-config.js
Labels: Priority: High

#328 fix(FEC-8572): change the way the player compute text tracks font size
  flow-typed/interfaces/engine.js
  src/engines/html5/html5.js
  src/player.js
  src/track/external-captions-handler.js
  src/track/text-style.js
  src/track/text-track-display.js
Labels: Priority: High, Type: Bug

#336 feat(FEC-8675): add ad progress and buffer event to player
  src/ads/ad-event-type.js
Labels: Type: Feature

#342 fix(FEC-8865): the captions style change is not applied on iOS
  src/player.js
Labels: Priority: Medium

#341 fix(FEC-8858): the captions languages in list displayed twice
  src/track/external-captions-handler.js
Labels: Priority: High, Type: Bug
