Repository kaltura/playkit-js, pull requests merged in 2019-06, with the labels that each got.

#364 feat(FEC-9055): Add custom Playback rate support
  docs/configuration.md
  src/player.js
  test/src/player.spec.js
  test/src/utils/test-utils.js
Labels: Type: Feature

#365 fix(FEC-9177): Smart TV showed as mobile device
  src/utils/env.js
Labels: Type: Bug

#366 fix(FEC-9187): LG TV different behavior for LIVE
  src/engines/html5/media-source/adapters/native-adapter.js
Labels: Type: Bug

#350 feat(FEC-8631): bumper plugin
  flow-typed/interfaces/ads-controller-provider.js
  flow-typed/interfaces/ads-plugin-controller.js
  flow-typed/types/ad-options.js
  src/ads/ad-event-type.js
  src/ads/ad.js
  src/ads/ads-controller.js
  src/controller/controller-provider.js
  src/player.js
Labels: Priority: High, Type: Feature

#368 fix(FEC-9192): post bumper doesn't play
  flow-typed/interfaces/ads-plugin-controller.js
  src/ads/ads-controller.js
Labels: Priority: High, Type: Bug

#367 feat(FEC-9023): More logger options
  docs/configuration.md
  flow-typed/types/log-level.js
  flow-typed/types/player-options.js
  karma.conf.js
  src/player-config.js
  src/player.js
  src/utils/logger.js
  test/src/player.spec.js
Labels: Type: Bug
