Repository kaltura/playkit-js, pull requests merged in 2019-04, with the labels that each got.

#353 fix(FEC-8826): fullscreen implementation moved to core
  docs/configuration.md
  flow-typed/types/playback-config.js
  src/assets/style.css
  src/event/event-type.js
  src/fullscreen/fullscreen-controller.js
  src/player-config.js
  src/player.js
  test/src/player.spec.js
Labels: Type: Maintenance

#354 fix(FEC-8826): pass html element from api and there isn't check for ios in isfullscreen method
  src/fullscreen/fullscreen-controller.js
  src/player.js
  test/src/player.spec.js
Labels: Type: Bug

#355 fix(FEC-9021): [iOS] - different behaviour after closing fullscreen and enter fullscreen again
  src/fullscreen/fullscreen-controller.js
Labels: Type: Bug

#356 fix(FEC-9037): When entering/exiting fullscreen, the events are sent twice
  src/fullscreen/fullscreen-controller.js
Labels: Type: Bug

#324 feat: engine decorator
  flow-typed/interfaces/engine-decorator-provider.js
  flow-typed/interfaces/engine.js
  flow-typed/interfaces/media-source-adapter.js
  src/ads/ads-controller.js
  src/assets/style.css
  src/engines/base-engine-decorator.js
  src/engines/html5/html5.js
  src/engines/html5/media-source/adapters/native-adapter.js
  src/engines/html5/media-source/base-media-source-adapter.js
  src/event/event-type.js
  src/player.js
  src/playkit.js
Labels: Type: Feature
