Repository kaltura/playkit-js, pull requests merged in 2019-02, with the labels that each got.

#343 fix(FEC-8874): captions look and feel issues
  src/player.js
  src/track/text-track-display.js
  test/src/player.spec.js
Labels: Priority: Medium

#344 docs(FEC-8809): new keySystem DRM option
  docs/configuration.md
  docs/drm-system.md
  flow-typed/interfaces/media-source-adapter.js
  flow-typed/types/drm-config.js
Labels: Priority: High

#347 fix(FEC-8381): when external caption http request fails, the error message is not clear
  src/track/external-captions-handler.js
Labels: Priority: Medium

#348 fix(FEC-8911): autoplay is not working on Samsung Native (built-in) browser
  src/assets/blob-source.json
  src/engines/html5/capabilities/html5-autoplay.js
Labels: Priority: High, Type: Bug

#349 fix(FEC-8565): AUTOPLAY_FAILED event is dispatched after play-pause on slow network
  src/player.js
Labels: Type: Bug
