Repository kaltura/playkit-js, pull requests merged in 2019-10, with the labels that each got.

#403 fix(FEC-9313): weird behaviour IOS when configuration autoplay native
  flow-typed/interfaces/engine-capabilty.js
  src/engines/html5/capabilities/html5-autoplay.js
  src/engines/html5/html5.js
  src/player.js
Labels: Type: Bug

#404 fix(FEC-9385): new ad layout, in playlist the ads playing for one entry only
  src/ads/ads-controller.js
Labels: Priority: High, Type: Bug

#405 fix(FEC-9333): when playing a playlist and closing the countdown window, the next entry starts automatically
  src/player.js
  src/state/state-manager.js
Labels: Priority: High, Type: Bug

#409 fix(FEC-9379): add detection for chromium Edge
  src/utils/env.js
Labels: Type: Bug

#407 feat(FEC-9293): ad waterfalling
  flow-typed/interfaces/ads-controller.js
  src/ads/ad-event-type.js
  src/ads/ads-controller.js
Labels: Priority: High
