Repository kaltura/playkit-js, pull requests merged in 2020-08, with the labels that each got.

#463 feat(FEC-10057): move the plugin manager to kaltura player
  docs/api.md
  docs/configuration.md
  flow-typed/interfaces/ads-controller-provider.js
  flow-typed/interfaces/ads-controller.js
  flow-typed/interfaces/ads-plugin-controller.js
  flow-typed/interfaces/middleware-provider.js
  flow-typed/interfaces/plugin.js
  flow-typed/interfaces/preset-components-provider.js
  flow-typed/types/ad-break.js
  flow-typed/types/ad-pod.js
  flow-typed/types/ad.js
  flow-typed/types/advertising-config.js
  flow-typed/types/player-options.js
  flow-typed/types/plugins-config.js
  flow-typed/types/ui-component.js
  src/ads/ad-break.js
  src/ads/ad.js
  src/ads/ads-controller.js
  src/controller/controller-provider.js
  src/engines/engine-decorator.js
  src/player-config.js
  src/player.js
  src/playkit.js
  src/plugin/base-plugin.js
  src/plugin/plugin-manager.js
  src/state/state-manager.js
  test/src/ads/ads-controller.spec.js
  test/src/configs/plugins.json
  test/src/player.spec.js
  test/src/plugin/base-plugin.spec.js
  test/src/plugin/plugin-manager.spec.js
  test/src/plugin/test-plugins/colors-plugin.js
  test/src/plugin/test-plugins/numbers-plugin.js
Labels: Priority: High, Type: Feature

#476 chore: downgrade to standard-version 6
  package.json
  yarn.lock
Labels: Priority: High

#478 feat(FEC-10146): Add native video track analytics data
  flow-typed/types/video-dimensions.js
  src/engines/html5/media-source/adapters/native-adapter.js
Labels: Type: Feature
