Repository kaltura/playkit-js, pull requests merged in 2021-02, with the labels that each got.

#540 feat(FEC-10970): expose vpaid field on ad object
  flow-typed/types/ad-options.js
Labels: Priority: High, Type: Feature

#542 feat(FEC-10915): let shaka and hls.js use their own default bandwidth estimators
  docs/configuration.md
  src/player-config.js
Labels: Priority: High

#544 fix(FEC-11037): multiple decorator exist after destroy plugin with decorator
  flow-typed/types/engine-decorator-provider.js
  src/engines/engine-decorator-manager.js
  src/engines/engine-decorator-provider.js
  src/engines/engine-decorator.js
  src/player.js
  src/playkit.js
  test/src/engines/engine-deorator.spec.js
  test/src/engines/test-engine-decorator-providers.js
Labels: Type: Bug
